#!/usr/bin/env python

from utils.logger import logger
from utils.servers import GunicornServe
from utils.arg_parser import APIArgParser

if __name__ == '__main__':
    logger.info("Begin serve")

    arg_parser = APIArgParser()
    args = arg_parser.get_arguments()
    models_folder_path = args.model_base_path / 'model'

    server = GunicornServe(
        f"{args.project_name} {args.run_tag}",
        str(models_folder_path),
        args.model_server_workers,
        args.model_server_timeout,
    )
    server.start_server()

    logger.info("End serve")
