#!/usr/bin/env python

from services.artifacts import ExperimentArtifacts
from services.experiment import Experiment
from services.model import ProjectModel
from utils.arg_parser import LocalArgParser
from utils.logger import logger


if __name__ == '__main__':
    logger.info(f"Begin train.py")

    arg_parser = LocalArgParser()
    args = arg_parser.get_arguments()

    run_tag = f"{args.project_name}-{args.run_tag}"
    dataset_path = args.data_path

    model_name = dataset_path.stem
    model = ProjectModel()

    artifacts_handler = ExperimentArtifacts(
        run_tag=run_tag,
        model_name=model_name,
        base_path=args.output_base_path,
    )
    experiment = Experiment(
        model=model,
        data_path=dataset_path,
        artifacts_handler=artifacts_handler,
    )
    experiment.run()

    logger.info(f"End train.py")
